from __future__ import annotations

from typing import Any, Dict

from .nodes import (
    AddSurfacePointsNode,
    AutoOrientationsNode,
    CleanGeoTableNode,
    ConvertOrientationAnglesNode,
    ComputeGemPyModelNode,
    ConfigureStructuralFrameNode,
    CreateGemPyModelNode,
    SharedVoxelGridNode,
    ExtractGemPyArrayNode,
    LoadKadiFileNode,
    LoadUploadedFileNode,
    LoadGemPyModelJsonNode,
    MergeTablesNode,
    PreviewDataNode,
    PlotGemPy2DNode,
    PlotGemPy3DNode,
    HexMeshToVoxelGridNode,
    MeshToVoxelModelNode,
    ClipVoxelModelByMaskNode,
    MergeVoxelModelsNode,
    InteractiveGemPyModelDataEditorNode,
    ExtractVoxelBoundariesNode,
    PyVistaClippedLayerViewerNode,
    CombineMeshesNode,
    ThickenMeshNode,
    SampleGeoTableNode,
    SaveArrayNode,
    SaveGemPyModelJsonNode,
    SaveTableCsvNode,
    SetGemPyOptionsNode,
    SetFiniteFaultNode,
    SetTopographyNode,
    SetGemPyGridNode,
    UploadFileToKadiNode,
    UploadGeoDTStructureVersionToKadiNode,
    ValidateGeoTableNode,
)
from .local_top_layer_nodes import RemoveLocalTopLayerNode
from .voxel_repair_nodes import (
    OGSIdentifyFullMeshNode,
    RepairReorderVoxelMeshNode,
)

NODE_REGISTRY = {
    cls.type_name: cls()
    for cls in [
        LoadUploadedFileNode,
        LoadGemPyModelJsonNode,
        LoadKadiFileNode,
        MergeTablesNode,
        ValidateGeoTableNode,
        ConvertOrientationAnglesNode,
        CleanGeoTableNode,
        SampleGeoTableNode,
        InteractiveGemPyModelDataEditorNode,
        PreviewDataNode,
        PlotGemPy2DNode,
        PlotGemPy3DNode,
        PyVistaClippedLayerViewerNode,
        CombineMeshesNode,
        ThickenMeshNode,
        RemoveLocalTopLayerNode,
        HexMeshToVoxelGridNode,
        MeshToVoxelModelNode,
        RepairReorderVoxelMeshNode,
        OGSIdentifyFullMeshNode,
        ClipVoxelModelByMaskNode,
        MergeVoxelModelsNode,
        ExtractVoxelBoundariesNode,
        SaveTableCsvNode,
        CreateGemPyModelNode,
        SharedVoxelGridNode,
        ConfigureStructuralFrameNode,
        SetFiniteFaultNode,
        AddSurfacePointsNode,
        AutoOrientationsNode,
        SetTopographyNode,
        SetGemPyGridNode,
        SetGemPyOptionsNode,
        ComputeGemPyModelNode,
        ExtractGemPyArrayNode,
        SaveArrayNode,
        SaveGemPyModelJsonNode,
        UploadFileToKadiNode,
        UploadGeoDTStructureVersionToKadiNode,
    ]
}

# Backward-compatible execution alias for project files saved with v30/v31/v32.
if "Visualization" in NODE_REGISTRY:
    NODE_REGISTRY["PreviewData"] = NODE_REGISTRY["Visualization"]


def p(name: str, label: str, kind: str = "text", default: Any = "", options=None, help_text: str = "") -> Dict[str, Any]:
    return {"name": name, "label": label, "kind": kind, "default": default, "options": options or [], "help": help_text}


def port(name: str, label: str, kind: str, multiple: bool = False) -> Dict[str, Any]:
    return {"name": name, "label": label, "kind": kind, "multiple": multiple}


DEFAULT_GROUPS_JSON = """[
  {"index": 0, "name": "Fault_series", "elements": ["F2"], "relation": "FAULT"},
  {"index": 1, "name": "Quaternary_series", "elements": ["Quaternary"], "relation": "ONLAP"},
  {"index": 2, "name": "Buntsandstein_series", "elements": ["Buntsandstein"], "relation": "ERODE"},
  {"index": 3, "name": "Zechstein_series", "elements": ["Zechstein"], "relation": "ERODE"},
  {"index": 4, "name": "Rotliegend_series", "elements": ["Rhyolith"], "relation": "ERODE"},
  {"index": 5, "name": "Crystalline_Basement_series", "elements": ["Granit", "Granodiorit", "Flasergranitoid", "Diorit, Gabbro", "Orthogneis", "Amphibolit"], "relation": "ERODE"}
]"""

DEFAULT_EXTENT = "[476621, 491762, 5487135, 5507123, -200, 700]"


DEFAULT_FAULT_RELATIONS_JSON = """{
  "enabled": false,
  "relations": []
}"""

DEFAULT_FINITE_FAULTS_JSON = """[
  {
    "enabled": true,
    "group_name": "Fault_series",
    "group_index": "",
    "center": "486530,5494995,105",
    "radius": "3000,4000,100",
    "max_slope": "1",
    "transform_position": "0,0,0",
    "transform_rotation": "0,0,0",
    "transform_scale": "1,1,1"
  }
]"""

DEFAULT_MANUAL_POINTS_JSON = """[
  {"mode": "grid", "element": "PraePerm", "xs": "486800,486000,484000,482000,480000,478000", "ys": "5487500,5488750,5490000,5491250,5492500,5493750,5495000,5496250,5497500,5498750,5500000,5501250,5502500,5503750,5505000,5506250,5507500", "z": 700},
  {"mode": "single", "element": "GG", "x": 486358, "y": 5494995, "z": 133}
]"""

DEFAULT_LAYER_STYLES_JSON = """[
  {"id": 0, "label": "layer1", "color": "#7a1fa2", "opacity": 0.5},
  {"id": 1, "label": "layer2", "color": "#d17ac6", "opacity": 0.3},
  {"id": 2, "label": "layer3", "color": "#1F70CC", "opacity": 0.5},
  {"id": 3, "label": "layer4", "color": "#EECA3B", "opacity": 0.5}
]"""

NODE_TYPES = [
    {
        "type": "LoadUploadedFile",
        "title": "Load Uploaded File",
        "category": "Input",
        "description": "Read an uploaded table, mesh, raster or array file. Tables produce table output; meshes produce mesh output; all files also produce a file output.",
        "inputs": [],
        "outputs": [
            port("table", "table", "table"),
            port("mesh", "mesh", "mesh"),
            port("file", "file", "file"),
        ],
        "params": [
            p("file_id", "Uploaded file", "file_select", ""),
            p("file_type", "File type", "select", "auto", ["auto", "csv", "xlsx", "json", "gempy", "mesh", "vtk", "vtp", "vtu", "vti", "stl", "ply", "obj", "raster", "tif", "tiff", "npy"]),
            p("sheet_name", "Excel sheet name", "text", ""),
        ],
    },
    {
        "type": "LoadGemPyModelJson",
        "title": "Load GemPy Model",
        "category": "Input",
        "description": "Load a GemPy .gempy model definition with gp.load_model; legacy JsonIO .json files remain readable. Recompute solutions after loading.",
        "inputs": [port("file", "GemPy model .gempy or legacy .json, optional", "file")],
        "outputs": [port("geo_model", "geo model", "geo_model")],
        "params": [
            p("file_id", "Uploaded GemPy model file", "file_select", "", help_text="Optional if a file is connected. Use a .gempy file saved by Save GemPy Model, or a legacy JsonIO .json file."),
        ],
    },
    {
        "type": "LoadKadiFile",
        "title": "Load from Kadi",
        "category": "Input",
        "description": "Download a CSV/XLSX table, a PyVista-readable mesh, or a GemPy model file from a Kadi record.",
        "inputs": [],
        "outputs": [
            port("table", "table", "table"),
            port("mesh", "mesh", "mesh"),
            port("file", "downloaded file", "file"),
        ],
        "params": [
            p("record_id", "Kadi record id", "number", "49744"),
            p("file_name", "File name", "text", "local_geology.csv"),
            p("file_type", "File type", "select", "auto", ["auto", "csv", "xlsx", "json", "gempy", "mesh", "vtk", "vtp", "vtu", "vti", "stl", "ply", "obj"]),
            p("sheet_name", "Excel sheet name", "text", "", help_text="Optional; only used when loading Excel files."),
        ],
    },
    {
        "type": "MergeTables",
        "title": "Merge Tables",
        "category": "Data",
        "description": "Concatenate multiple tables.",
        "inputs": [port("tables", "tables", "table", multiple=True)],
        "outputs": [port("table", "merged", "table"), port("report", "merge report", "report")],
        "params": [
            p("axis", "Axis", "number", 0),
            p("ignore_index", "Ignore index", "boolean", True),
            p("add_source_column", "Add source column for checking", "boolean", False),
            p("source_column", "Source column name", "text", "_merge_source"),
            p("manual_order", "Manual order, optional", "text", ""),
        ],
    },
    {
        "type": "ValidateGeoTable",
        "title": "Validate Geological Table",
        "category": "Data",
        "description": "Check required GemPy columns and basic coordinate/orientation quality.",
        "inputs": [port("table", "table", "table")],
        "outputs": [port("table", "table", "table"), port("report", "report", "report")],
        "params": [
            p("table_kind", "Table kind", "select", "auto", ["auto", "surface_points", "orientations", "fault_points", "fault_orientations"]),
        ],
    },
    {
        "type": "ConvertOrientationAngles",
        "title": "Convert Orientation Angles",
        "category": "Data",
        "description": "Convert orientation tables with dip/azimuth columns into GemPy gradient-vector columns G_x, G_y, G_z before merging with existing G-vector orientation data.",
        "inputs": [port("table", "orientation table", "table")],
        "outputs": [port("table", "converted orientation table", "table"), port("report", "conversion report", "report")],
        "params": [
            p("azimuth_col", "Azimuth column", "text", "auto", help_text="auto detects azimuth, az, dip_direction, dipdirection, direction."),
            p("dip_col", "Dip column", "text", "auto", help_text="auto detects dip, dip_angle, dipangle, inclination."),
            p("polarity_col", "Polarity column", "text", "auto", help_text="Optional. auto detects polarity/pole_polarity/sense. Missing polarity is treated as 1."),
            p("formation_col", "Formation column", "text", "formation"),
            p("azimuth_is_dip_direction", "Azimuth is dip direction", "boolean", True, help_text="If unchecked, azimuth is interpreted as strike and converted to dip direction by adding 90 degrees."),
            p("overwrite_existing_gradients", "Overwrite existing G columns", "boolean", False, help_text="If false, only rows missing G_x/G_y/G_z are filled from dip/azimuth."),
            p("normalize_vectors", "Normalize output vectors", "boolean", True),
            p("formation_to_str", "Convert formation to string", "boolean", True),
            p("drop_angle_columns", "Drop dip/azimuth columns after conversion", "boolean", False),
            p("drop_incomplete_gradient_rows", "Drop rows still missing G values", "boolean", False),
        ],
    },
    {
        "type": "CleanGeoTable",
        "title": "Clean Geological Table",
        "category": "Data",
        "description": "Convert coordinate/gradient columns to numbers and optionally remove invalid rows.",
        "inputs": [port("table", "table", "table")],
        "outputs": [port("table", "cleaned", "table"), port("report", "report", "report")],
        "params": [
            p("coord_cols", "Coordinate columns", "text", "X,Y,Z"),
            p("grad_cols", "Gradient columns", "text", "G_x,G_y,G_z"),
            p("formation_col", "Formation column", "text", "formation"),
            p("formation_to_str", "Convert formation to string", "boolean", True, help_text="Recommended for GemPy. Prevents numeric formation names such as 0.0 from causing name_id_map KeyError."),
            p("numeric_xyz", "Convert XYZ to numeric", "boolean", True),
            p("numeric_gradients", "Convert gradients to numeric", "boolean", True),
            p("drop_missing_xyz", "Drop missing XYZ", "boolean", True),
            p("remove_zero_gradients", "Remove zero gradients", "boolean", False),
        ],
    },
    {
        "type": "SampleGeoTable",
        "title": "Sample Geological Data",
        "category": "Data",
        "description": "Responsive stratified formation-aware sampling. Default fast method avoids slow/hanging KMeans on large tables.",
        "inputs": [port("table", "table", "table")],
        "outputs": [port("table", "sampled", "table"), port("report", "sampling report", "report")],
        "params": [
            p("group_col", "Group column", "text", "formation"),
            p("feature_cols", "Feature columns", "text", "X,Y,Z"),
            p("n", "Target rows", "number", 100),
            p("method", "Sampling method", "select", "fast", ["fast", "random", "kmeans"], help_text="fast is recommended and avoids sklearn KMeans stalls; kmeans keeps the old behavior."),
            p("allocation", "Allocation", "select", "equal", ["equal", "proportional", "min_distance"]),
            p("random_state", "Random state", "number", 42),
            p("na_strategy", "NA strategy", "select", "median", ["median", "drop"]),
            p("scale", "Feature scaling", "select", "none", ["none", "standard"]),
        ],
    },
    {
        "type": "InteractiveGemPyModelDataEditor",
        "title": "Interactive GeoModel Data Editor",
        "category": "GemPy",
        "description": "Interactively select, modify, delete and add points/orientations inside an already-created GemPy GeoModel using GemPy's add/modify/delete APIs.",
        "inputs": [port("geo_model", "geo model", "geo_model")],
        "outputs": [port("geo_model", "edited geo model", "geo_model"), port("report", "interactive editor report", "report")],
        "params": [
            p("operations_json", "Interactive edits", "geological_point_editor", "[]", help_text="Use the visual editor below. The queued edits are applied to the GeoModel through GemPy API calls when this node runs."),
            p("auto_create_missing_element", "Try to create missing element", "boolean", False, help_text="Advanced. If you type a new element name, the node will try to create a new structural element/group using the installed GemPy API before adding the point."),
            p("new_element_relation", "New element relation", "select", "ERODE", ["ERODE", "ONLAP", "FAULT"], help_text="Used only when auto-creating a missing element is supported by the current GemPy version."),
            p("fail_on_edit_error", "Fail if any edit is not applied", "boolean", True, help_text="Recommended. The node will stop with a clear error instead of silently returning an unchanged model if a GemPy API edit fails."),
        ],
    },
    {
        "type": "Visualization",
        "title": "Visualization",
        "category": "View",
        "description": "Universal visualization node with a single input. Connect any table, file, raster/TIF, VTK/VTU/VTP mesh, array, voxel output, report, GeoModel or solution.",
        "inputs": [port("data", "data", "any")],
        "outputs": [port("preview", "preview report", "report")],
        "params": [
            p("rows", "Table rows", "number", 15),
            p("mesh_scalars", "Mesh scalars", "text", "auto", help_text="Use auto to prefer MaterialIDs/id/lithology/layer. Or enter a cell/point data name."),
            p("filter_by_scalar_values", "Only show selected scalar values", "boolean", False, help_text="Display-only mesh filter. Enable this and enter values below to show only matching cells/points. The upstream mesh is not changed."),
            p("scalar_filter_values", "Scalar values to show", "text", "", help_text="Numeric value such as 2, or several comma-separated values such as 2,5,7. Uses the Mesh scalars field above."),
            p("show_edges", "Show mesh edges in preview", "boolean", False),
            p("generate_thumbnail", "Generate inline thumbnail", "boolean", True),
        ],
    },

    {
        "type": "PlotGemPy2D",
        "title": "Plot GemPy 2D",
        "category": "View",
        "description": "Create a 2D GemPy plot as a PNG. If gempy_viewer fails, it can fall back to a solution array slice.",
        "inputs": [port("geo_model", "geo model", "geo_model"), port("solution", "solution, optional fallback", "gempy_solution")],
        "outputs": [port("file", "PNG plot", "file")],
        "params": [
            p("direction", "Direction", "select", "y", ["x", "y", "z"]),
            p("cell_number", "Cell number, optional", "number", ""),
            p("show_data", "Show data", "boolean", True),
            p("show_lith", "Show lithology", "boolean", True),
            p("show_boundaries", "Show boundaries", "boolean", True),
            p("show_scalar", "Show scalar field", "boolean", False),
            p("fallback_array", "Fallback array", "text", "lith_block"),
            p("reshape", "Fallback reshape", "shape3", ""),
            p("dpi", "DPI", "number", 160),
            p("file_name", "File name", "text", "gempy_2d_plot.png"),
        ],
    },
    {
        "type": "PlotGemPy3D",
        "title": "Plot GemPy 3D",
        "category": "View",
        "description": "Prepare a PyVista/GemPy 3D popup for the computed GeoModel.",
        "inputs": [port("geo_model", "geo model", "geo_model")],
        "outputs": [
            port("report", "viewer/report", "report"),
            port("mesh", "surface mesh", "mesh"),
            port("file", "saved surface mesh", "file"),
        ],
        "params": [
            p("show_data", "Show data", "boolean", True),
            p("show_lith", "Show lithology", "boolean", True),
            p("show_surfaces", "Show surfaces", "boolean", True),
            p("show_topography", "Show topography", "boolean", True),
            p("show_boundaries", "Show boundaries", "boolean", True),
            p("save_surface_mesh", "Save surface mesh", "boolean", True, help_text="Save the extracted computed GemPy structural surfaces as a downloadable mesh."),
            p("surface_mesh_file_name", "Surface mesh file name", "text", "gempy_3d_surfaces.vtp", help_text="Use .vtp for PolyData surfaces or .vtu for an unstructured-grid version."),
        ],
    },

    {
        "type": "SharedVoxelGrid",
        "title": "Shared Voxel Grid",
        "category": "Mesh / Voxel",
        "description": "Define one world-coordinate voxel origin and spacing for GemPy, clipping, voxelization and merging.",
        "inputs": [],
        "outputs": [port("grid", "shared grid", "voxel_grid_spec")],
        "params": [
            p("origin", "Grid origin [x,y,z]", "text", "[0, 0, 0]"),
            p("voxel_size", "Voxel size X / all axes", "text", "2.5"),
            p("voxel_size_y", "Voxel size Y, optional", "text", ""),
            p("voxel_size_z", "Voxel size Z, optional", "text", ""),
        ],
    },
    {
        "type": "PyVistaClippedLayerViewer",
        "title": "Clipping Tool",
        "category": "View",
        "description": "Clip either GemPy voxel/layer output or an existing PyVista/VTK mesh with optional shell and DEM/topography meshes, then export the clipped mesh.",
        "inputs": [
            port("geo_model", "computed geo model, optional", "geo_model"),
            port("shared_grid", "shared grid, optional", "voxel_grid_spec"),
            port("input_mesh", "mesh to clip, optional", "mesh"),
            port("clip_mesh", "clipping shell mesh", "mesh"),
            port("topography_mesh", "DEM/topography mesh", "mesh"),
        ],
        "outputs": [
            port("report", "viewer/report", "report"),
            port("mesh", "clipped layer mesh", "mesh"),
            port("file", "saved clipped mesh", "file"),
        ],
        "params": [
            p("clip_mesh_file_id", "Clipping shell mesh, optional", "file_select", "", help_text="Optional shell_PraePerm.vtp or another PyVista-readable clipping surface. Leave empty to skip this clipping step."),
            p("topography_mesh_file_id", "DEM/topography mesh, optional", "file_select", "", help_text="Optional dem.vtp. When provided, it is used for topographic clipping by default, not displayed as a separate mesh."),
            p("cell_data_name", "Cell data name", "text", "id", help_text="For GeoModel mode this selects the layer id array. For mesh-input mode it is used for preview when present; otherwise the node auto-detects a scalar."),
            p("mesh_scalars", "Mesh-input preview scalars", "text", "auto", help_text="Only used when clipping an existing mesh input and cell_data_name is not present."),
            p("layer_styles_json", "Layer ids / colors / opacity", "layer_styles", DEFAULT_LAYER_STYLES_JSON),
            p("invert", "Shell clip invert", "boolean", False),
            p("topography_clip_enabled", "Use DEM/topography for clipping", "boolean", True),
            p("topography_invert", "DEM/topography clip invert", "boolean", False),
            p("crop_to_topography_xy", "Crop to DEM XY bounds before DEM clip", "boolean", True),
            p("crinkle", "clip_surface crinkle", "boolean", True),
            p("clean_output_mesh", "Clean output mesh", "boolean", True),
            p("show_edges", "Show layer edges", "boolean", False),
            p("show_base_gempy", "Also show base GemPy 3D scene", "boolean", False),
            p("show_clip_mesh", "Show clipping shell mesh", "boolean", False),
            p("show_topography_mesh", "Show DEM/topography mesh", "boolean", False),
            p("output_file_name", "Output clipped mesh file", "text", "clipped_gempy_layers.vtu", help_text="If the clipped result is a surface/PolyData but the name ends with .vtu, it is automatically saved as .vtp."),
        ],
    },
    {
        "type": "ThickenMesh",
        "title": "Thicken Mesh",
        "category": "View",
        "description": "Thicken a surface mesh along its normals by a user-defined buffer distance. Creates a shell surface with optional side walls for open meshes.",
        "inputs": [
            port("mesh", "mesh", "mesh"),
        ],
        "outputs": [
            port("mesh", "thickened mesh", "mesh"),
            port("file", "thickened mesh file", "file"),
            port("report", "thickening report", "report"),
        ],
        "params": [
            p("buffer_distance", "Buffer distance", "number", 10.0, help_text="Thickness distance in the same unit as the mesh coordinates."),
            p("mode", "Thickening mode", "select", "symmetric", ["symmetric", "outward", "inward"], help_text="symmetric offsets half the distance to both sides; outward/inward are one-sided along/opposite the normals."),
            p("close_sides", "Close sides for open surfaces", "boolean", True, help_text="Adds side-wall faces along boundary edges of open surfaces."),
            p("triangulate_input", "Triangulate input surface", "boolean", True),
            p("consistent_normals", "Consistent normals", "boolean", True),
            p("auto_orient_normals", "Auto-orient normals", "boolean", True),
            p("flip_normals", "Flip normals", "boolean", False),
            p("clean_input", "Clean input surface", "boolean", True),
            p("clean_output", "Clean output mesh", "boolean", True),
            p("mesh_scalars", "Preview scalars", "text", "auto"),
            p("show_edges", "Show edges in preview", "boolean", True),
            p("output_file_name", "Output mesh file", "text", "thickened_mesh.vtp"),
        ],
    },
    {
        "type": "RemoveLocalTopLayer",
        "title": "Remove Local Top Layer",
        "category": "Mesh / Voxel",
        "description": "Remove the upper layer of a volume/voxel mesh relative to the local DEM elevation at every XY position. No global cutoff Z is used.",
        "inputs": [
            port("input_mesh", "volume/voxel mesh, optional", "mesh"),
            port("topography_mesh", "DEM/topography mesh", "mesh"),
        ],
        "outputs": [
            port("mesh", "mesh without local top layer", "mesh"),
            port("file", "saved result mesh", "file"),
            port("lowered_topography", "local cutoff DEM", "mesh"),
            port("lowered_topography_file", "saved local cutoff DEM", "file"),
            port("report", "local top-layer report", "report"),
        ],
        "params": [
            p("input_mesh_file_id", "Volume/voxel mesh file, optional", "file_select", "", help_text="Use this only when no mesh is connected to input_mesh."),
            p("topography_mesh_file_id", "DEM/topography file", "file_select", "", help_text="Required when no DEM mesh is connected to topography_mesh."),
            p("top_layer_thickness", "Top-layer thickness", "number", 20.0, help_text="At every XY location, cells are retained only below DEM_Z(X,Y) minus this thickness."),
            p("selection_mode", "Cell selection mode", "select", "cell_center", ["cell_center", "all_points", "any_point"], help_text="cell_center is recommended for voxel meshes. all_points removes every cell that crosses the local cutoff; any_point is less strict."),
            p("dem_sampling_method", "DEM sampling method", "select", "auto", ["auto", "regular_grid", "nearest"], help_text="auto uses linear interpolation for complete regular-grid DEMs and nearest DEM points otherwise."),
            p("crop_to_dem_xy", "Crop to DEM XY bounds", "boolean", True),
            p("triangulate_dem", "Triangulate lowered DEM output", "boolean", True),
            p("clean_lowered_dem", "Clean lowered DEM output", "boolean", False),
            p("clean_output_mesh", "Clean result mesh", "boolean", True),
            p("mesh_scalars", "Preview scalars", "text", "auto"),
            p("show_edges", "Show edges in preview", "boolean", True),
            p("output_file_name", "Result mesh file", "text", "mesh_without_local_top_20m.vtu"),
            p("lowered_dem_file_name", "Local cutoff DEM file", "text", "dem_local_top_minus_20m.vtp"),
        ],
    },
    {
        "type": "CombineMeshes",
        "title": "Combine Meshes",
        "category": "View",
        "description": "Combine multiple PyVista/VTK mesh outputs into one mesh. Useful for combining clipped results from several GemPy models into a single exportable mesh.",
        "inputs": [
            port("meshes", "meshes", "mesh", multiple=True),
        ],
        "outputs": [
            port("mesh", "combined mesh", "mesh"),
            port("file", "combined mesh file", "file"),
            port("report", "combine report", "report"),
        ],
        "params": [
            p("mesh_file_ids", "Additional mesh file ids", "text", "", help_text="Optional comma-separated file ids from uploaded/output VTK meshes."),
            p("combine_mode", "Combine mode", "select", "merge", ["merge", "multiblock_combine"]),
            p("extract_surface", "Extract surface before combining", "boolean", False, help_text="Useful when combining volumetric VTU grids as surface-only output."),
            p("merge_points", "Merge coincident points", "boolean", False, help_text="Usually false for combining separate clipped model parts. Set true to weld coincident points."),
            p("tolerance", "Merge/clean tolerance", "number", 0.0),
            p("clean_inputs", "Clean each input mesh", "boolean", False),
            p("clean_output", "Clean combined mesh", "boolean", True),
            p("add_source_id", "Add source_id array", "boolean", True, help_text="Adds source_id to cell and point data so parts can be distinguished after combining."),
            p("create_reindexed_element_id", "Create unique element id scalar", "boolean", True, help_text="Creates a new cell-data scalar where each input mesh's original element/material ids are remapped to globally unique ids."),
            p("reindex_source_scalar", "Source scalar for reindexing", "text", "auto", help_text="Use auto to detect existing combined_element_id first, then element_id/id/MaterialIDs/lith_block. Or enter the exact scalar name to remap."),
            p("reindexed_scalar_name", "New scalar name", "text", "combined_element_id"),
            p("reindex_scope", "Reindex scope", "select", "source_and_element", ["source_and_element", "global_element"], help_text="source_and_element makes element_id=1 from different input meshes become different ids. global_element keeps same original values together."),
            p("reindex_start_id", "First new id", "number", 1),
            p("reindex_missing_value", "Missing id value", "number", -1),
            p("preserve_numeric_arrays", "Preserve numeric arrays", "boolean", True, help_text="Adds NaN-filled missing numeric arrays before merging so cell-data columns are not dropped."),
            p("mesh_scalars", "Preview scalars", "text", "auto"),
            p("show_edges", "Show edges in preview", "boolean", False),
            p("output_file_name", "Output mesh file", "text", "combined_mesh.vtu", help_text="In auto mode, surface/PolyData outputs requested as .vtu are saved as .vtp because PyVista cannot save PolyData as .vtu."),
            p("auto_extract_surface_for_vtp", "Auto extract surface for .vtp", "boolean", True, help_text="If output is .vtp and the combined mesh is volumetric, extract its surface before saving."),
        ],
    },
    {
        "type": "RepairReorderVoxelMesh",
        "title": "Repair and Reorder Voxel Mesh",
        "category": "Mesh / Voxel",
        "description": "Repair the bottom of a regular voxel mesh, remove unsupported/floating columns, optionally remove one outer pure-material layer, reorder cells and nodes, and optionally reindex sorted unique MaterialIDs consecutively from 0. The grid reference can be inferred from the actual cell-center lattice, so a constant coordinate offset relative to bottom_z does not cause a false regular-grid error.",
        "inputs": [
            port("mesh", "voxel mesh / file", "any"),
        ],
        "outputs": [
            port("mesh", "repaired and reordered mesh", "mesh"),
            port("voxel_model", "repaired voxel model", "mesh"),
            port("file", "repaired mesh .vtu", "file"),
            port("report", "repair/reorder report", "report"),
        ],
        "params": [
            p("mesh_file_id", "Voxel mesh file, optional", "file_select", "", help_text="Optional uploaded mesh file. Leave empty when a mesh/file output is connected."),
            p("material_array", "Material cell-data array", "text", "MaterialIDs", help_text="Cell-data scalar used for material grouping, outer-layer removal, sorting, and optional ID conversion."),
            p("bottom_z", "Configured bottom Z", "number", -200.0, help_text="Cells whose lower face lies below this elevation are removed. The lowest valid voxel centers are expected at bottom_z + dz/2."),
            p("lowest_layers_to_repair", "Lowest layers to inspect", "number", 20, help_text="Number of bottom voxel layers inspected when detecting enclosed holes. Enclosed missing columns are filled continuously to reconnect with existing voxels."),
            p("repair_bottom_holes", "Repair enclosed bottom holes", "boolean", True, help_text="Detect enclosed gaps near the bottom and create missing voxel cells using nearby cell and point data."),
            p("remove_floating_columns", "Remove floating columns", "boolean", True, help_text="Remove complete vertical columns whose lowest voxel is not connected to the configured bottom."),
            p("remove_one_outer_material_layer", "Remove one outer pure-material layer", "boolean", True, help_text="Single pass only: remove initially exposed outer columns when all cells in the column use the selected outer material ID."),
            p("outer_layer_material_id", "Outer layer MaterialID", "number", 1, help_text="Material value used by the optional single-pass outer-column removal."),
            p("spacing_decimals", "Spacing inference decimals", "number", 6, help_text="Cell-center coordinates are rounded to this precision before median voxel spacing is inferred."),
            p("grid_tolerance", "Regular-grid residual tolerance", "number", 0.0001, help_text="Maximum accepted deviation after fitting the regular-grid center lattice. A constant origin shift is handled by Grid reference mode and should not require a larger tolerance."),
            p("grid_reference_mode", "Grid reference mode", "select", "auto_from_centers", ["auto_from_centers", "configured_bottom_strict"], help_text="Recommended: auto_from_centers infers the actual X/Y/Z center-lattice phase from the mesh. configured_bottom_strict preserves the old requirement that the first Z center equals bottom_z + dz/2."),
            p("bottom_tolerance", "Bottom clipping tolerance", "number", 0.000001, help_text="Tolerance used only when removing cells whose lower face lies below Configured bottom Z."),
            p("maximum_xy_source_radius", "Maximum XY source-search radius", "number", 20, help_text="Maximum number of neighboring voxel columns searched when assigning cell data to newly repaired voxels."),
            p("merge_point_tolerance", "Patch point-merge tolerance", "number", 0.00000001, help_text="Tolerance used when merging repaired patch vertices with existing voxel-grid vertices."),
            p("remove_stale_mapping_arrays", "Remove stale mapping arrays", "boolean", True, help_text="Remove bulk_node_ids, bulk_element_ids, vtkOriginal* arrays, merge-source arrays, and other mappings invalidated by repair/reordering."),
            p("add_node_material_ids", "Add NodeMaterialIDs", "boolean", True, help_text="Assign every reordered node the material of the first reordered cell in which that node occurs."),
            p("keep_original_order_ids", "Keep original order IDs", "boolean", False, help_text="Add OriginalNodeIDs and OriginalElementIDs for tracing the reordered entities back to the input order."),
            p("reindex_material_ids_from_zero", "Reindex MaterialIDs from 0", "boolean", True, help_text="Sort the unique original material values and map them consecutively to 0, 1, ..., n-1. For example, 1-6 becomes 0-5 and 10,20,40 becomes 0,1,2. NodeMaterialIDs use the same mapping."),
            p("preview_scalar", "Preview scalar", "text", "MaterialIDs"),
            p("show_edges", "Show edges in preview", "boolean", True),
            p("file_name", "Output file name", "text", "repaired_reordered_voxel_model.vtu"),
        ],
    },
    {
        "type": "OGSIdentifyFullMesh",
        "title": "OGS Identify Full Mesh",
        "category": "Mesh / Voxel",
        "description": "Run the official OGS identifySubdomains executable using the same full-dimensional VTU as both bulk mesh and subdomain mesh. The result remains a full 3D mesh and receives point-data bulk_node_ids and cell-data bulk_element_ids. This implements Part 2 of the notebook.",
        "inputs": [
            port("mesh", "full repaired mesh / file", "any"),
        ],
        "outputs": [
            port("mesh", "OGS-identified full mesh", "mesh"),
            port("file", "identified full mesh .vtu", "file"),
            port("report", "OGS identify report", "report"),
        ],
        "params": [
            p("mesh_file_id", "Full mesh file, optional", "file_select", "", help_text="Optional uploaded VTU/VTK mesh. Leave empty when the repaired mesh output is connected."),
            p("executable_path", "identifySubdomains executable path", "text", "", help_text="Optional exact path to identifySubdomains.exe or identifySubdomains. When set, this takes precedence over OGS bin directory and PATH."),
            p("ogs_bin_dir", "OGS bin directory", "text", "", help_text="Folder containing identifySubdomains(.exe). Leave empty when the executable is available on PATH."),
            p("search_length", "Search length", "number", 0.000001, help_text="Value passed to identifySubdomains with -s. The notebook default is 1e-6."),
            p("preview_scalar", "Preview scalar", "text", "MaterialIDs"),
            p("show_edges", "Show edges in preview", "boolean", True),
            p("file_name", "Output file name", "text", "identified_full_mesh.vtu"),
        ],
    },
    {
        "type": "ExtractVoxelBoundaries",
        "title": "Extract Voxel Boundaries",
        "category": "Output",
        "description": "Extract top, bottom, north, south, east and west boundary meshes from a voxel grid. Copies all compatible input cell-data and point-data arrays to the generated boundaries and saves both VTP and VTU formats. Uses median-spacing quantized indexing to avoid fake boundary columns from tiny coordinate noise.",
        "inputs": [port("mesh", "voxel grid / mesh", "mesh")],
        "outputs": [
            port("report", "boundary report", "report"),
            port("top", "top boundary .vtp", "file"),
            port("bottom", "bottom boundary .vtp", "file"),
            port("north", "north boundary .vtp", "file"),
            port("south", "south boundary .vtp", "file"),
            port("east", "east boundary .vtp", "file"),
            port("west", "west boundary .vtp", "file"),
            port("side_mesh", "side mesh .vtp", "file"),
            port("full_shell", "full shell .vtp", "file"),
            port("top_vtu", "top boundary .vtu", "file"),
            port("bottom_vtu", "bottom boundary .vtu", "file"),
            port("north_vtu", "north boundary .vtu", "file"),
            port("south_vtu", "south boundary .vtu", "file"),
            port("east_vtu", "east boundary .vtu", "file"),
            port("west_vtu", "west boundary .vtu", "file"),
            port("side_mesh_vtu", "side mesh .vtu", "file"),
            port("full_shell_vtu", "full shell .vtu", "file"),
            port("side_mesh_obj", "side mesh object", "mesh"),
            port("full_shell_obj", "full shell object", "mesh"),
            port("selected_preview", "selected boundary preview manifest", "file"),
        ],
        "params": [
            p("mesh_file_id", "Voxel grid file, optional", "file_select", "", help_text="Optional .vtu/.vtk voxel grid. Leave empty when connecting Hex Mesh to Voxel Grid.voxel_grid."),
            p("cell_data_name", "Material cell data name", "text", "MaterialIDs"),
            p("decimals", "Center coordinate rounding decimals", "number", 8, help_text="Used only for robust spacing/min-center inference. Grid indices are quantized by median voxel spacing, so tiny coordinate noise will not create fake grid columns."),
            p("add_top_risers", "Add vertical risers on stepped top", "boolean", True),
            p("triangulate_shells", "Triangulate side/full shell", "boolean", True),
            p("clean_tolerance", "Clean tolerance for side/full shell", "number", 1e-9),
            p("output_prefix", "Output file prefix", "text", "voxel"),
            p("show_edges", "Show edges in preview", "boolean", True),
            p("show_top", "Show top", "boolean", True),
            p("show_bottom", "Show bottom", "boolean", True),
            p("show_north", "Show north", "boolean", True),
            p("show_south", "Show south", "boolean", True),
            p("show_east", "Show east", "boolean", True),
            p("show_west", "Show west", "boolean", True),
            p("color_top", "Top color", "text", "red"),
            p("color_bottom", "Bottom color", "text", "blue"),
            p("color_north", "North color", "text", "green"),
            p("color_south", "South color", "text", "yellow"),
            p("color_east", "East color", "text", "orange"),
            p("color_west", "West color", "text", "purple"),
        ],
    },
    {
        "type": "MeshToVoxelModel",
        "title": "Mesh to Voxel Model",
        "category": "Mesh / Voxel",
        "description": "Voxelize PyVista-readable meshes into a regular voxel-grid model. Use inside-surface mode for closed solids or distance-to-surface mode for open fault/sheet meshes.",
        "inputs": [
            port("mesh", "mesh", "mesh"),
            port("reference_geo_model", "reference geo model, optional", "geo_model"),
            port("shared_grid", "shared grid, optional", "voxel_grid_spec"),
        ],
        "outputs": [
            port("voxel_model", "voxel model", "mesh"),
            port("voxel_grid", "voxel grid", "mesh"),
            port("file", "voxel model file", "file"),
            port("report", "voxelization report", "report"),
        ],
        "params": [
            p("mesh_file_id", "Mesh file, optional", "file_select", "", help_text="Optional if a mesh is connected. Supports PyVista-readable mesh files."),
            p("voxel_size", "Voxel size X / all axes", "text", "", help_text="Leave empty/auto to infer. If reference_geo_model is connected, uses the same regular-grid voxel size as the Clipping Tool GeoModel volume."),
            p("voxel_size_y", "Voxel size Y, optional", "text", ""),
            p("voxel_size_z", "Voxel size Z, optional", "text", ""),
            p("target_cells_longest_axis", "Auto target cells on longest axis", "number", 80),
            p("max_voxels", "Max candidate voxels", "number", 2000000),
            p("padding", "Padding around mesh bounds", "number", 0.0),
            p("voxelization_mode", "Voxelization mode", "select", "inside_surface", ["inside_surface", "distance_to_surface"], help_text="inside_surface is for closed solids. distance_to_surface is recommended for open fault/sheet meshes and avoids ray-casting fringe artifacts."),
            p("distance_buffer", "Distance radius override (surface mode)", "text", "", help_text="Distance-to-surface radius, NOT total thickness. After Thicken Mesh, leave empty to preserve its thickness: voxelization uses the retained centre surface and half the Thicken thickness, without adding another buffer. An explicit value overrides that half-width (total target width = 2 × radius). For an unthickened surface only, the empty default is 0.75 × min voxel size. Coarse voxels may under-resolve thin features."),
            p("distance_chunk_size", "Distance chunk size", "number", 200000),
            p("source_scalar", "Source scalar", "text", "auto", help_text="Cell/point scalar from the mesh to transfer to voxel cells."),
            p("output_scalar_name", "Output scalar name", "text", "MaterialIDs"),
            p("inside_tolerance", "Inside tolerance", "number", 1e-6),
            p("check_surface", "Check closed surface", "boolean", False, help_text="Enable to make PyVista validate closed surface. For open surfaces, use Thicken Mesh first."),
            p("invert_inside", "Invert inside/outside", "boolean", False),
            p("clean_output", "Clean output", "boolean", True),
            p("show_edges", "Show edges in preview", "boolean", True),
            p("file_name", "Output file name", "text", "mesh_voxel_model.vtu"),
        ],
    },
    {
        "type": "ClipVoxelModelByMask",
        "title": "Clip Voxel Model by Mask",
        "category": "Mesh / Voxel",
        "description": "Remove voxels from a base voxel model using another voxel model as a mask/occluder. Useful for clipping away the covering layer so the mask model becomes visible on the outer surface after merging.",
        "inputs": [
            port("base_voxel_model", "base voxel model to clip", "mesh"),
            port("mask_voxel_model", "mask / model to reveal", "mesh"),
        ],
        "outputs": [
            port("voxel_model", "clipped voxel model", "mesh"),
            port("voxel_grid", "clipped voxel grid", "mesh"),
            port("removed_voxels", "removed voxels, optional", "mesh"),
            port("file", "clipped voxel file", "file"),
            port("report", "clip report", "report"),
        ],
        "params": [
            p("clip_mode", "Clip mode", "select", "same_xy_column_all_z", ["exact_overlap", "same_xy_column_all_z", "same_xy_column_above_mask", "same_xy_column_below_mask", "same_xy_column_inside_mask_z_range"], help_text="exact_overlap removes only identical voxel positions. same_xy_column_all_z cuts a vertical window through the base model where the mask exists. above/below remove only one side in Z."),
            p("xy_expand_cells", "XY expand cells", "number", 0, help_text="Expands the mask columns by this many cells in X/Y, useful for making the revealed window slightly wider."),
            p("z_margin_cells", "Z margin cells", "number", 0),
            p("resample_mask_to_base_grid", "Resample mask to base grid", "boolean", True, help_text="When mask and base voxel sizes differ, expand mask voxels to covered base-grid cells."),
            p("voxel_size", "Manual voxel size X / all axes, optional", "text", "", help_text="Leave empty to infer from the base voxel model."),
            p("voxel_size_y", "Manual voxel size Y, optional", "text", ""),
            p("voxel_size_z", "Manual voxel size Z, optional", "text", ""),
            p("preview_scalar", "Preview scalar", "text", "auto"),
            p("output_removed_voxels", "Also output removed voxels", "boolean", False),
            p("clean_output", "Clean output", "boolean", True),
            p("show_edges", "Show edges in preview", "boolean", True),
            p("file_name", "Output file name", "text", "clipped_voxel_model.vtu"),
        ],
    },
    {
        "type": "MergeVoxelModels",
        "title": "Merge Voxel Models",
        "category": "Mesh / Voxel",
        "description": "Merge several voxel-grid models into one true voxel grid. Inputs with different grid sizes are resampled onto a common target voxel grid before overlap resolution and source-aware reindexing.",
        "inputs": [
            port("voxel_models", "voxel models", "mesh", multiple=True),
            port("shared_grid", "shared grid, optional", "voxel_grid_spec"),
        ],
        "outputs": [
            port("voxel_model", "merged voxel model", "mesh"),
            port("voxel_grid", "merged voxel grid", "mesh"),
            port("file", "merged voxel file", "file"),
            port("report", "merge report", "report"),
        ],
        "params": [
            p("input_scalar_map_json", "Input scalar per voxel model", "voxel_scalar_map", "[]", help_text="After connecting/running input voxel models, choose which cell-data scalar from each model should be merged."),
            p("cell_data_name", "Fallback input scalar", "text", "auto", help_text="Used when no per-input scalar is selected. Use auto to choose a reasonable scalar from each input."),
            p("output_scalar_name", "Output reindexed scalar name", "text", "MaterialIDs", help_text="The selected input scalar values are remapped into this new scalar as consecutive IDs starting at 1."),
            p("reindex_scope", "Reindex scope", "select", "source_and_value", ["source_and_value", "global_value"], help_text="source_and_value keeps source-based ID separation. global_value keeps equal original values together across inputs."),
            p("reindex_start_id", "First output scalar ID", "number", 1),
            p("first_input_wins", "First input overwrites later inputs", "boolean", True, help_text="Recommended. If voxel models overlap, the first connected input has priority."),
            p("target_voxel_size_mode", "Target voxel size mode", "select", "smallest_input", ["smallest_input", "first_input", "largest_input", "median_input"], help_text="smallest_input preserves detail when voxel models have different grid sizes. first_input keeps the old behavior."),
            p("resample_to_target_grid", "Resample inputs to target grid", "boolean", True, help_text="When enabled, large source voxels are expanded to all target voxels they cover instead of being represented by one center point."),
            p("max_merged_voxels", "Max merged voxels", "number", 2000000),
            p("voxel_size", "Manual voxel size X / all axes, optional", "text", "", help_text="Overrides Target voxel size mode when set."),
            p("voxel_size_y", "Manual voxel size Y, optional", "text", ""),
            p("voxel_size_z", "Manual voxel size Z, optional", "text", ""),
            p("default_value", "Default value if scalar missing", "number", 1),
            p("clean_output", "Clean output", "boolean", True),
            p("show_edges", "Show edges in preview", "boolean", True),
            p("file_name", "Output file name", "text", "merged_voxel_model.vtu"),
        ],
    },
    {
        "type": "HexMeshToVoxelGrid",
        "title": "Hex Mesh to Voxel Grid",
        "category": "Output",
        "description": "Convert an 8-node hexahedral mesh to a VTK VOXEL unstructured grid, preserving cell_data, following your original notebook method.",
        "inputs": [port("mesh", "mesh, optional", "mesh")],
        "outputs": [port("voxel_grid", "voxel grid", "mesh"), port("file", "VTU file", "file")],
        "params": [
            p("mesh_file_id", "Mesh file, optional", "file_select", "", help_text="Optional .vtu/.vtk mesh file. Leave empty when connecting a mesh output from PyVista Clipped Layer Viewer."),
            p("skip_non_hex", "Skip non-hex cells", "boolean", False),
            p("clean_after", "Clean output grid", "boolean", True),
            p("tolerance", "Degenerate-cell tolerance", "number", 1e-8),
            p("material_scalar", "Material scalar for coloring", "text", "auto", help_text="Use 'auto' to prefer MaterialIDs/id/lithology. Do not use cell_ids unless you want an index-colored grid."),
            p("output_material_name", "Output material cell-data name", "text", "MaterialIDs", help_text="The chosen material scalar is copied to this cell-data name so the PyVista preview uses the same style as your original notebook."),
            p("show_edges", "Show voxel edges in preview", "boolean", True),
            p("file_name", "Output VTU file name", "text", "gempy_volume_with_topo_voxel_grid.vtu"),
        ],
    },
    {
        "type": "SaveTableCsv",
        "title": "Save Table CSV",
        "category": "Output",
        "description": "Export a table as CSV and expose a download link.",
        "inputs": [port("table", "table", "table")],
        "outputs": [port("file", "file", "file")],
        "params": [p("file_name", "File name", "text", "table.csv")],
    },
    {
        "type": "CreateGemPyModel",
        "title": "Create GemPy Model",
        "category": "GemPy",
        "description": "Create a GemPy GeoModel from surface points and orientations.",
        "inputs": [
            port("surface_points", "surface points", "table"),
            port("orientations", "orientations", "table"),
            port("shared_grid", "shared grid, optional", "voxel_grid_spec"),
        ],
        "outputs": [port("geo_model", "geo model", "geo_model")],
        "params": [
            p("project_name", "Project name", "text", "Hessian 3D"),
            p("auto_extent_from_data", "Auto extent from input points", "boolean", True, help_text="When enabled, model extent is calculated from connected surface points and orientations using X/Y/Z min/max plus padding."),
            p("extent_padding_percent", "Extent padding (%)", "number", 5.0, help_text="Padding applied on each min/max side when auto extent is used. Default: 5%."),
            p("extent_user_overridden", "Manual extent override", "boolean", False, help_text="Internal/state flag. Turns on automatically when you edit Model extent manually; disables auto extent until you click Fill extent from data."),
            p("extent", "Model extent", "extent6", DEFAULT_EXTENT, help_text="Auto-filled from connected surface points/orientations when possible. Edit any value to switch to manual override."),
            p("refinement", "Refinement", "number", 3),
            p("resolution", "Resolution, optional", "resolution3", "", help_text="When enabled, this overrides refinement with [nx, ny, nz]."),
            p("apply_surface_point_nugget", "Apply surface point nugget", "boolean", False, help_text="Optional. Calls gp.modify_surface_points(geo_model=geo_model, nugget=...) after gp.create_geomodel. Default is off to match GemPy examples."),
            p("surface_point_nugget", "Surface point nugget", "number", 0.01),
        ],
    },
    {
        "type": "ConfigureStructuralFrame",
        "title": "Configure Structural Frame",
        "category": "GemPy",
        "description": "Use stack mapping for order/elements and structural groups for relations.",
        "inputs": [port("geo_model", "geo model", "geo_model")],
        "outputs": [port("geo_model", "geo model", "geo_model")],
        "params": [
            p("anisotropy", "Anisotropy", "select", "NONE", ["unchanged", "NONE"]),
            p("mapping_json", "Stack mapping", "mapping_builder", "", help_text="Leave empty to auto-generate a generic one-element-per-series mapping from the connected GeoModel. Fill/edit rows to manually control series order and grouping."),
            p("groups_json", "Structural groups / relations", "structural_groups", "[]", help_text="Generic default is empty. When Stack mapping is empty and auto mode is enabled, groups are inferred from the connected GeoModel. When Stack mapping is filled, this only sets relation for each mapped series."),
            p("auto_mapping_from_geo_model", "Auto mapping from connected GeoModel", "boolean", True, help_text="When Stack mapping is empty, infer series/elements from the incoming GeoModel instead of using project-specific defaults."),
            p("auto_groups_from_mapping", "Auto structural groups from mapping", "boolean", True, help_text="When Structural groups is empty, infer relation rows from the current mapping. Fault-looking names become FAULT, basement-looking names become BASEMENT, others ERODE."),
            p("mapping_auto_initialized", "Mapping was auto-filled", "boolean", False, help_text="Internal/state flag. When true, automatic fill will not run again unless you click Fill from connected GeoModel."),
            p("mapping_user_overridden", "Manual mapping override", "boolean", False, help_text="Internal/state flag. Turns on automatically when you edit mapping rows; prevents auto-fill from overwriting your edits."),
            p("groups_user_overridden", "Manual groups override", "boolean", False, help_text="Internal/state flag. Turns on when you clear/edit relation groups manually."),
            p("fault_relations_json", "Fault relations matrix", "fault_relations_builder", DEFAULT_FAULT_RELATIONS_JSON, help_text="Click checkboxes to define geo_model.structural_frame.fault_relations. Rows are faulting series; columns are affected series."),
            p("remove_default_formation", "Remove default_formation", "boolean", True),
        ],
    },

    {
        "type": "SetFiniteFault",
        "title": "Set Finite Fault",
        "category": "GemPy",
        "description": "Assign finite fault data to selected fault structural groups using GemPy ellipsoid_3d_factory and FaultsData.",
        "inputs": [port("geo_model", "geo model", "geo_model")],
        "outputs": [port("geo_model", "geo model", "geo_model")],
        "params": [
            p("clear_existing", "Clear existing finite fault data first", "boolean", False),
            p("finite_faults_json", "Finite fault definitions", "finite_fault_builder", DEFAULT_FINITE_FAULTS_JSON, help_text="Select a structural group and define center/radius/max slope/transform. This corresponds to assigning group.faults_input_data in your notebook."),
        ],
    },
    {
        "type": "AddSurfacePoints",
        "title": "Add Surface Points",
        "category": "GemPy",
        "description": "Manually add single points or x-y grid points to an existing GemPy GeoModel before compute_model.",
        "inputs": [port("geo_model", "geo model", "geo_model"), port("points_table", "points table, optional", "table")],
        "outputs": [port("geo_model", "geo model", "geo_model")],
        "params": [
            p("points_json", "Manual surface points", "surface_points_builder", DEFAULT_MANUAL_POINTS_JSON, help_text="Add single point rows or grid rows. Grid rows expand every x with every y at the chosen z, matching the gp.add_surface_points loops in your notebook."),
        ],
    },
    {
        "type": "AutoOrientations",
        "title": "Auto Orientations",
        "category": "GemPy",
        "description": "Generate orientations from surface-point coordinates for selected elements.",
        "inputs": [port("geo_model", "geo model", "geo_model")],
        "outputs": [port("geo_model", "geo model", "geo_model")],
        "params": [p("element_names", "Element names", "text", "Quaternary,Granit")],
    },
    {
        "type": "SetTopography",
        "title": "Set / Preview Topography",
        "category": "GemPy",
        "description": "Set topography from file, arrays/table, random topography within current model extent, or preview current topography.",
        "inputs": [
            port("geo_model", "geo model", "geo_model"),
            port("topography_file", "topography file, optional", "file"),
            port("topography_table", "topography XYZ table, optional", "table"),
        ],
        "outputs": [port("geo_model", "geo model", "geo_model"), port("report", "topography report", "report")],
        "params": [
            p("mode", "Mode", "select", "file", ["file", "arrays", "random", "preview"]),
            p("topography_file_id", "Uploaded topo file", "file_select", ""),
            p("filepath", "Local filepath", "text", ""),
            p("topography_points_json", "Topography points JSON", "textarea", "[]", help_text="For arrays mode: list of [x,y,z] or objects {x,y,z}. A connected table with X/Y/Z can be used instead."),
            p("topography_resolution", "Random/topography resolution", "text", "[50, 50]", help_text="Used for random mode when supported by the installed GemPy version."),
            p("random_z_fraction_min", "Random min z fraction", "number", 0.6, help_text="Fraction of the current model z-range. 0 is z_min, 1 is z_max."),
            p("random_z_fraction_max", "Random max z fraction", "number", 1.0, help_text="Random topography is clipped to the model z-range."),
            p("fractal_dimension", "Random fractal dimension", "number", 2.0),
        ],
    },
    {
        "type": "SetGemPyGrid",
        "title": "Set GemPy Grid",
        "category": "GemPy",
        "description": "Configure GemPy grid: section grid, custom grid, centered grid, or active grid selection.",
        "inputs": [port("geo_model", "geo model", "geo_model"), port("grid_points", "grid/center points table, optional", "table")],
        "outputs": [port("geo_model", "geo model", "geo_model"), port("report", "grid report", "report")],
        "params": [
            p("mode", "Mode", "select", "activate", ["section", "custom", "centered", "activate"]),
            p("section_name", "Section name", "text", "section"),
            p("section_start", "Section start [x,y]", "text", "[0, 0]"),
            p("section_end", "Section end [x,y]", "text", "[1000, 1000]"),
            p("section_resolution", "Section resolution [nx,ny]", "text", "[100, 80]"),
            p("custom_points_json", "Custom grid XYZ points", "textarea", "[]", help_text="For custom mode: list of [x,y,z]. A connected X/Y/Z table can be used instead."),
            p("centers_json", "Centered grid centers", "textarea", "[[0, 0, 0]]", help_text="For centered mode: list of center [x,y,z]. A connected X/Y/Z table can be used instead."),
            p("centered_radius", "Centered grid radius", "text", "[100, 100, 100]"),
            p("centered_resolution", "Centered grid resolution", "text", "[10, 10, 10]"),
            p("active_grids", "Active grids", "text", "regular", help_text="Comma-separated grid names, e.g. regular,topography,sections,custom,centered."),
            p("reset_active_grids", "Reset active grids first", "boolean", True),
        ],
    },
    {
        "type": "SetGemPyOptions",
        "title": "Set Interpolation Options",
        "category": "GemPy",
        "description": "Set interpolation and engine-related options before compute_model.",
        "inputs": [port("geo_model", "geo model", "geo_model")],
        "outputs": [port("geo_model", "geo model", "geo_model")],
        "params": [
            p("number_octree_levels_surface", "Octree levels surface", "number", "", help_text="Leave empty to keep GemPy internal default."),
            p("kernel_range", "Kernel range", "number", "", help_text="Leave empty to keep GemPy internal default."),
            p("octree_error_threshold", "Octree error threshold", "number", "", help_text="Leave empty to keep GemPy internal default."),
            p("evaluation_chunk_size", "Evaluation chunk size", "number", "", help_text="Leave empty to keep GemPy internal default."),
            p("verbose", "Verbose", "select", "unchanged", ["unchanged", "true", "false"], help_text="Leave unchanged to keep GemPy internal default."),
            p("compute_condition_number", "Compute condition number", "select", "unchanged", ["unchanged", "true", "false"], help_text="Leave unchanged to keep GemPy internal default."),
            p("uni_degree", "Universal drift degree", "number", "", help_text="Leave empty to keep GemPy internal default."),
            p("mesh_extraction", "Mesh extraction", "select", "unchanged", ["unchanged", "true", "false"], help_text="Leave unchanged to keep GemPy internal default. Compute GemPy Model controls surface extraction for the run."),
            p("kernel_function", "Kernel function", "text", "", help_text="Leave empty to keep GemPy internal default."),
        ],
    },
    {
        "type": "ComputeGemPyModel",
        "title": "Compute GemPy Model",
        "category": "GemPy",
        "description": "Run gp.compute_model and expose geo_model + solution outputs.",
        "inputs": [port("geo_model", "geo model", "geo_model")],
        "outputs": [port("geo_model", "geo model", "geo_model"), port("solution", "solution", "gempy_solution")],
        "params": [
            p("backend", "Backend", "select", "PYTORCH", ["PYTORCH", "numpy"]),
            p("dtype", "Dtype", "select", "float64", ["float64", "float32"]),
            p("mesh_extraction", "Extract surface meshes", "boolean", True, help_text="Default on so show_boundaries/surface plotting works. Disable this when GemPy fails in dual_contouring/mask_generation."),
            p("retry_without_mesh_extraction", "Retry without surface meshes", "boolean", True),
        ],
    },
    {
        "type": "ExtractGemPyArray",
        "title": "Extract GemPy Array",
        "category": "GemPy",
        "description": "Extract lith_block or another raw_arrays attribute from GemPy solution.",
        "inputs": [port("solution", "solution", "gempy_solution")],
        "outputs": [port("array", "array", "array")],
        "params": [
            p("output_name", "raw_arrays attribute", "text", "lith_block"),
            p("reshape", "Reshape, optional", "shape3", "[64, 64, 64]"),
        ],
    },
    {
        "type": "SaveGemPyModelJson",
        "title": "Save GemPy Model",
        "category": "Output",
        "description": "Save the GemPy model definition as a .gempy file using gp.save_model. Computed solutions are not included.",
        "inputs": [port("geo_model", "geo model", "geo_model")],
        "outputs": [port("file", "GemPy model .gempy", "file"), port("report", "save report", "report")],
        "params": [
            p("file_name", "File name", "text", "gempy_model.gempy"),
        ],
    },
    {
        "type": "SaveArray",
        "title": "Save Array",
        "category": "Output",
        "description": "Export a NumPy array as .npy or .csv.",
        "inputs": [port("array", "array", "array")],
        "outputs": [port("file", "file", "file")],
        "params": [
            p("format", "Format", "select", "npy", ["npy", "csv"]),
            p("file_name", "File name", "text", "array.npy"),
        ],
    },
    {
        "type": "UploadGeoDTStructureVersionToKadi",
        "title": "Upload GeoDT Structure Version to Kadi",
        "category": "Output",
        "description": "Create a new GeoDT structure-model version record in Kadi, update the current-version description record, and upload the voxel volume plus all extracted boundary meshes with fixed simulation names.",
        "inputs": [
            port("volume", "Hex Mesh to Voxel Grid.file", "file"),
            port("south", "south boundary file", "file"),
            port("north", "north boundary file", "file"),
            port("bottom", "bottom boundary file", "file"),
            port("top", "top boundary file", "file"),
            port("west", "west boundary file", "file"),
            port("east", "east boundary file", "file"),
            port("side_mesh", "side_mesh file", "file"),
            port("full_shell", "full_shell file", "file"),
        ],
        "outputs": [port("report", "Kadi upload report", "report")],
        "params": [
            p("title", "Record title", "text", "GeoDT Input Structure Model"),
            p("description", "Record description", "textarea", "Data from the structural model workflow, including the structural model, the total surfaces and all sub-surfaces."),
            p("subject", "Subject metadata", "text", "Structure model in voxel grid from GemPy"),
            p("collection_id", "Collection ID", "number", 7238),
            p("description_record_id", "Description record ID", "number", 80295, help_text="This record receives/updates the metadatum 'Record ID of the current version'."),
            p("version", "Version", "text", "0.1"),
            p("tag", "Tag", "text", "geolab"),
            p("update_description_record", "Update current-version description record", "boolean", True),
            p("add_group_roles", "Add notebook group roles", "boolean", True, help_text="Adds group roles 143/Admin, 302/Editor and 122/Member."),
            p("force_upload", "Overwrite files if names exist", "boolean", True),
            p("dry_run", "Dry run, prepare files only", "boolean", False, help_text="Prepare the correctly named files and report what would be uploaded, without creating a Kadi record."),
        ],
    },
    {
        "type": "UploadFileToKadi",
        "title": "Upload File to Kadi",
        "category": "Output",
        "description": "Upload an exported file to a Kadi record.",
        "inputs": [port("file", "file", "file")],
        "outputs": [port("report", "report", "report")],
        "params": [
            p("record_id", "Target Kadi record id", "number", "49742"),
            p("file_name", "Target file name", "text", ""),
            p("force", "Overwrite", "boolean", True),
        ],
    },
]
